repos:
    # From prek
  - repo: builtin
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 6305bf1ae645ab7541be4f5028a86239316178eb  # frozen: 26.1.0
    hooks:
      - id: black
  - repo: https://github.com/trufflesecurity/trufflehog
    rev: 7f4e37db2d928c18ddd7ddf0604f8f7d1f5793ec  # frozen: v3.93.0
    hooks:
      - id: trufflehog
        stages: [pre-push, manual]
